version: "3"

services:

  amazons:
    container_name: amazons
    restart: unless-stopped
    build:
      context: amazons/
    env_file:
      - .env
    depends_on: 
      - amazons_db
    links:
      - amazons_db
    ports:
      - "0.0.0.0:${HOST_MACHINE_AMAZONS_PORT}:5000"
