version: "3"

services:

  amazons:
    container_name: amazons_dev
    restart: unless-stopped
    build:
      context: amazons/
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./amazons/app:/home/amazons/app
    ports:
      - "0.0.0.0:${HOST_MACHINE_AMAZONS_PORT}:${FLASK_RUN_PORT}"