"""games table

Revision ID: 781893fa68ae
Revises: 8f3c13bb2cad
Create Date: 2020-02-07 09:37:10.266944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781893fa68ae'
down_revision = '8f3c13bb2cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('white_user_id', sa.Integer(), nullable=True),
    sa.Column('black_user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['white_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_timestamp'), 'games', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_timestamp'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
