"""games table

Revision ID: 97e5deda8f7c
Revises: 781893fa68ae
Create Date: 2020-02-07 09:41:01.288560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e5deda8f7c'
down_revision = '781893fa68ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'games', 'user', ['black_user_id'], ['id'])
    # ### end Alembic commands ###
